resources:
  containers:
  - container: terraform_container
    image: lenisha/terraform-light

pool:
  vmImage: 'Ubuntu 20.04'

trigger:
  branches:
    include:
    - master

steps:
- script: |
    wget https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_amd64.zip
    sudo apt install zip -y
    unzip terraform_0.14.5_linux_amd64.zip
    sudo mv terraform /usr/local/bin/ 
    sudo chmod +x /usr/local/bin/terraform
    terraform -version 
  displayName: 'Get terraform' 

- script: |
    az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
  displayName: 'Enable AZ  Login'

- script: |
    cd deploy/terraform
    terraform -version
    terraform init -lock=false -input=false -backend-config=terraform.tfvars
    terraform plan
    terraform apply -auto-approve -input=false -var-file=terraform.tfvars
  displayName: 'Terraform init, plan and apply'
  env:
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
      

#- script: |
#    az storage blob delete-batch -s \$web --account-name $(BLOB_NAME)
#  displayName: 'clean content'


- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g gatsby-cli
  displayName: 'install gatsby'

- script: |
    npm install
    gatsby build
  displayName: 'gatsby build'
 
- script: |
    ls -la
    ls -la super
  displayName: 'Display contents'


# create the service principle...  
# az login
# az ad sp create-for-rbac --name wayne-superspecials

- script: |
    az storage blob upload-batch -s public -d \$web --account-name sscolestfsite
  displayName: 'copy content and site is ready'
  